# Traefik Configuration
# See: https://doc.traefik.io/traefik/

# Global configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# API and dashboard configuration
api:
  dashboard: true
  debug: false
  insecure: true  # Enable insecure mode for local testing

# Entry points configuration
entryPoints:
  web:
    address: ":80"
  
  websecure:
    address: ":443"

# Providers configuration
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik

# Middleware for VPN-only access
http:
  middlewares:
    vpn-only:
      ipWhiteList:
        sourceRange:
          - "10.8.0.0/24"  # WireGuard VPN network
          - "192.168.1.0/24" # Local network (optional)

# Logging configuration
log:
  level: INFO
  filePath: "/logs/traefik.log"

accessLog:
  filePath: "/logs/access.log"

# Metrics configuration (optional)
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true

# TLS configuration with Cloudflare Origin Certificates
tls:
  certificates:
    - certFile: /certs/cloudflare-origin.crt
      keyFile: /certs/cloudflare-origin.key

# Certificate resolvers (fallback)
certificatesResolvers:
  cloudflare:
    acme:
      email: ${CF_API_EMAIL}
      storage: /certs/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
