services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    volumes:
      - ./assets:/www/assets
    ports:
      - "8080:8080"
    user: "1000:1000"
    environment:
      - INIT_ASSETS=1
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
      - HOME_ASSISTANT_TOKEN=${HOME_ASSISTANT_TOKEN}
    env_file:
      - .env
    restart: unless-stopped

