- id: '1756658406869'
  alias: Evening Cozy Lights
  description: Turn on cozy lights 30 minutes before sunset
  triggers:
  - event: sunset
    offset: -00:30:00
    trigger: sun
  conditions: []
  actions:
  - action: light.turn_on
    target:
      device_id:
      - f5317caddef3f9d1279526c1b64a3b4b
      - 2878198d7d2a1f0f81e4f80242284ac8
    data:
      brightness_pct: 80
  - action: light.turn_on
    target:
      device_id:
      - e209b58eac25e36ca86ec61c2f1c9c81
      - 937a69fc55efe9077168dd25a87a1d6d
    data:
      brightness_pct: 25
      kelvin: 2700
  mode: single
- id: '1758031929542'
  alias: Sunrise Alarm Clock
  description: Turn lights on at 6:45 AM at full brightness (warm sunrise tone)
  triggers:
  - at: 06:43:00
    trigger: time
  actions:
  - action: light.turn_on
    target:
      device_id:
      - e209b58eac25e36ca86ec61c2f1c9c81
      - 937a69fc55efe9077168dd25a87a1d6d
    data:
      brightness_pct: 100
      color_temp: 370
  mode: single
