- id: '1756658406869'
  alias: Evening Cozy Lights
  description: Turn on cozy lights 30 minutes before sunset
  triggers:
  - event: sunset
    offset: -00:30:00
    trigger: sun
  conditions: []
  actions:
  - action: light.turn_on
    target:
      entity_id: light.living_room_spetsboj
    data:
      brightness_pct: 50
      color_temp_kelvin: 2695
  - action: light.turn_on
    target:
      entity_id: light.ikea_of_sweden_tradfri_bulb_e26_ww_globe_800lm_2
    data:
      brightness_pct: 40
  - action: light.turn_on
    target:
      entity_id: light.ikea_of_sweden_tradfri_bulb_e26_ww_globe_800lm
    data:
      brightness_pct: 70
  - action: light.turn_on
    target:
      entity_id:
      - light.h600b
      - light.h600b_2
    data:
      brightness_pct: 25
  mode: single
- id: '1758031929542'
  alias: Sunrise Alarm Clock
  description: Turn lights on at 6:45 AM at full brightness (warm sunrise tone)
  triggers:
  - at: 06:15:00
    trigger: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  actions:
  - action: light.turn_on
    target:
      entity_id:
      - light.h600b_2
      - light.h600b
    data:
      brightness_pct: 100
      color_temp_kelvin: 2700
  mode: single
- id: '1785291854907'
  alias: Living Room Lights Off
  description: Turn off the living room lights at 10:30 PM
  triggers:
  - at: '22:30:00'
    trigger: time
  conditions: []
  actions:
  - action: light.turn_off
    target:
      entity_id:
      - light.ikea_of_sweden_tradfri_bulb_e26_ww_globe_800lm
      - light.ikea_of_sweden_tradfri_bulb_e26_ww_globe_800lm_2
  mode: single
- id: '1785291854939'
  alias: Bedroom Lights Off
  description: Turn off the bedroom lights at 7:30 AM
  triggers:
  - at: 07:30:00
    trigger: time
  conditions: []
  actions:
  - action: light.turn_off
    target:
      entity_id:
      - light.h600b
      - light.h600b_2
  mode: single
