services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "3001:3001"       # Expose web UI on http://<pi_ip>:3001
    volumes:
      - ./data:/app/data  # Persistent data

