# Homepage Bookmarks Configuration
# See: https://homepage.0xcc.pw/configuration/bookmarks

- Group: Documentation
  icon: fas fa-book
  items:
    - name: Homepage Docs
      icon: fas fa-home
      url: https://homepage.0xcc.pw
      description: Homepage documentation
    - name: Home Assistant Docs
      icon: fas fa-home
      url: https://www.home-assistant.io/docs/
      description: Home Assistant documentation
    - name: Pi-hole Docs
      icon: fas fa-shield-alt
      url: https://docs.pi-hole.net/
      description: Pi-hole documentation

- Group: External Services
  icon: fas fa-external-link-alt
  items:
    - name: GitHub
      icon: fab fa-github
      url: https://github.com
      description: Code repository
    - name: Discord
      icon: fab fa-discord
      url: https://discord.com
      description: Communication platform
